Repository one-acre-fund/ph-ee-connector-mtn, pull requests merged in 2025-08, with the labels that each got.

#21 Extract the Correct Account Number & MSISDN from MTN Paybill Payload - CP-3769
  CHANGELOG.md
  build.gradle
  src/main/java/org/mifos/connector/mtn/camel/config/CamelProperties.java
  src/main/java/org/mifos/connector/mtn/camel/routes/PaybillRouteBuilder.java
  src/main/java/org/mifos/connector/mtn/dto/ChannelConfirmationRequest.java
  src/main/java/org/mifos/connector/mtn/dto/ChannelValidationRequest.java
  src/main/java/org/mifos/connector/mtn/dto/FinancialResourceInformationRequest.java
  src/main/java/org/mifos/connector/mtn/flowcomponents/state/PaybillConfirmationProcessor.java
  src/main/java/org/mifos/connector/mtn/utility/MtnUtils.java
  src/test/java/org/mifos/connector/mtn/camel/routes/PaybillRouteBuilderTest.java
  src/test/java/org/mifos/connector/mtn/utility/MtnUtilsTest.java
Labels: size/L, untested

#22 Move oafReference inside extension in MTN payment payload - CP-3774
  CHANGELOG.md
  build.gradle
  src/main/java/org/mifos/connector/mtn/camel/routes/PaybillRouteBuilder.java
  src/main/java/org/mifos/connector/mtn/dto/PaybillPaymentRequest.java
  src/main/java/org/mifos/connector/mtn/flowcomponents/state/PaybillConfirmationProcessor.java
  src/test/java/org/mifos/connector/mtn/camel/routes/PaybillRouteBuilderTest.java
  src/test/java/org/mifos/connector/mtn/flowcomponents/state/PaybillConfirmationProcessorTest.java
Labels: size/M, untested

#23 fix(CP-3784): Modify the namespace for payment endpoint response to match the request namespace
  CHANGELOG.md
  build.gradle
  src/main/java/org/mifos/connector/mtn/dto/FinancialResourceInformationRequest.java
  src/main/java/org/mifos/connector/mtn/dto/FinancialResourceInformationResponse.java
  src/main/java/org/mifos/connector/mtn/dto/PaybillPaymentRequest.java
  src/main/java/org/mifos/connector/mtn/dto/PaybillPaymentResponse.java
  src/main/java/org/mifos/connector/mtn/dto/PaymentCompletedRequest.java
  src/main/java/org/mifos/connector/mtn/dto/PaymentCompletedResponse.java
  src/main/java/org/mifos/connector/mtn/utility/MtnConstants.java
Labels: size/M

#24 Fix/cp 3784 fix basic auth in payment completed request
  CHANGELOG.md
  build.gradle
  src/main/java/org/mifos/connector/mtn/auth/AuthRoutes.java
  src/main/java/org/mifos/connector/mtn/camel/routes/PaybillRouteBuilder.java
  src/main/java/org/mifos/connector/mtn/exception/MissingConfigurationException.java
  src/main/java/org/mifos/connector/mtn/exception/MtnConnectorException.java
  src/main/java/org/mifos/connector/mtn/utility/ConnectionUtils.java
  src/test/java/org/mifos/connector/mtn/utility/ConnectionUtilsTest.java
Labels: size/L, untested
